// Package sanitise fixes encoding corruption in AI-generated text.
//
// The primary problem is Mojibake: UTF-8 bytes read as Windows-1252, producing
// sequences like â€¢ instead of • (bullet, U+2022). Two passes are applied:
//
//  1. Mojibake repair: replace known corrupted byte sequences with their ASCII equivalents.
//  2. Unicode normalisation: replace typographic Unicode characters with plain ASCII.
//
// Both passes target text destined for PDF rendering and database storage, where
// non-ASCII typographic characters can cause visible corruption or font fallback issues.
package sanitise

import (
	"strings"
	"unicode/utf8"
)

type replacement struct {
	from string
	to   string
}

// mojibakeMap maps known Windows-1252 misreadings of UTF-8 sequences to ASCII.
// Generated by taking each Unicode character's UTF-8 bytes and reading them as Windows-1252.
var mojibakeMap = []replacement{
	// U+2022 BULLET (E2 80 A2) → â€¢
	{"â\x80¢", "-"},
	// U+2014 EM DASH (E2 80 94) → â€"  (0x94 = " in W1252)
	{"â\x80\x94", "--"},
	// U+2013 EN DASH (E2 80 93) → â€"  (0x93 = " in W1252)
	{"â\x80\x93", "-"},
	// U+201C LEFT DOUBLE QUOTATION MARK (E2 80 9C) → â€œ
	{"â\x80\x9c", "\""},
	// U+201D RIGHT DOUBLE QUOTATION MARK (E2 80 9D) → â€
	{"â\x80\x9d", "\""},
	// U+2018 LEFT SINGLE QUOTATION MARK (E2 80 98) → â€˜
	{"â\x80\x98", "'"},
	// U+2019 RIGHT SINGLE QUOTATION MARK (E2 80 99) → â€™
	{"â\x80\x99", "'"},
	// U+2026 HORIZONTAL ELLIPSIS (E2 80 A6) → â€¦
	{"â\x80¦", "..."},
	// U+00B7 MIDDLE DOT (C2 B7) → Â·
	{"\xc2\xb7", "-"},
	// U+00A0 NO-BREAK SPACE (C2 A0) → Â (followed by non-breaking space byte)
	{"\xc2\xa0", " "},
	// U+2122 TRADE MARK SIGN (E2 84 A2) → â„¢
	{"â\x84¢", "TM"},
	// U+00AE REGISTERED SIGN (C2 AE) → Â®
	{"\xc2\xae", "(R)"},
	// U+00A9 COPYRIGHT SIGN (C2 A9) → Â©
	{"\xc2\xa9", "(C)"},
}

// unicodeMap replaces typographic Unicode characters with plain ASCII.
// Applied after mojibake repair, catching characters that arrived uncorrupted
// but are still unsuitable for PDF rendering with basic fonts.
var unicodeMap = []replacement{
	{"\u2022", "-"},   // BULLET
	{"\u25aa", "-"},   // BLACK SMALL SQUARE
	{"\u25b8", "-"},   // BLACK RIGHT-POINTING SMALL TRIANGLE
	{"\u2014", "--"},  // EM DASH
	{"\u2013", "-"},   // EN DASH
	{"\u00b7", "-"},   // MIDDLE DOT
	{"\u2018", "'"},   // LEFT SINGLE QUOTATION MARK
	{"\u2019", "'"},   // RIGHT SINGLE QUOTATION MARK
	{"\u201c", "\""},  // LEFT DOUBLE QUOTATION MARK
	{"\u201d", "\""},  // RIGHT DOUBLE QUOTATION MARK
	{"\u2026", "..."},  // HORIZONTAL ELLIPSIS
	{"\u00a0", " "},   // NO-BREAK SPACE
	{"\ufeff", ""},    // BOM / ZERO WIDTH NO-BREAK SPACE
	{"\u00ae", "(R)"}, // REGISTERED SIGN
	{"\u00a9", "(C)"}, // COPYRIGHT SIGN
	{"\u2122", "TM"},  // TRADE MARK SIGN
}

// ResumeText sanitises a single string from AI output for safe storage and
// PDF rendering. It runs mojibake repair → Unicode normalisation → UTF-8 validation.
func ResumeText(s string) string {
	if s == "" {
		return s
	}

	// Pass 1: Mojibake repair
	for _, r := range mojibakeMap {
		if strings.Contains(s, r.from) {
			s = strings.ReplaceAll(s, r.from, r.to)
		}
	}

	// Pass 2: Unicode → ASCII
	for _, r := range unicodeMap {
		if strings.Contains(s, r.from) {
			s = strings.ReplaceAll(s, r.from, r.to)
		}
	}

	// Pass 3: Strip any remaining invalid UTF-8 sequences
	if !utf8.ValidString(s) {
		s = strings.ToValidUTF8(s, "")
	}

	return s
}

// ResumeJSON walks an any value (parsed JSON) and applies ResumeText to every
// string leaf recursively. Pass the result of json.Unmarshal into any before
// storing or rendering AI content.
func ResumeJSON(v any) any {
	switch val := v.(type) {
	case string:
		return ResumeText(val)
	case []any:
		for i, item := range val {
			val[i] = ResumeJSON(item)
		}
		return val
	case map[string]any:
		for k, item := range val {
			val[k] = ResumeJSON(item)
		}
		return val
	}
	return v
}

// StripBOM removes a leading UTF-8 BOM (EF BB BF) from a byte slice.
func StripBOM(b []byte) []byte {
	if len(b) >= 3 && b[0] == 0xEF && b[1] == 0xBB && b[2] == 0xBF {
		return b[3:]
	}
	return b
}
